export const coursePosts = [
  {
    id: 101,
    author: 'Dr. Priya Sharma',
    avatar: 'PS',
    role: 'mentor',
    time: '2 hours ago',
    title: 'Module 4 Resources Updated: Advanced Ensemble Methods',
    tags: ['#announcement', '#module4', '#machine-learning'],
    badges: [{ text: 'Announcement', class: 'badge-announcement' }],
    content:
      "Just uploaded the new materials for Module 4: Advanced Ensemble Methods. Please review the Random Forest implementation case study before our live session on Thursday. I've included both Python and R examples for the implementation.",
    likes: 24,
    comments: 2,
    replies: [
      {
        author: 'Vikram Patel',
        avatar: 'VP',
        role: 'student',
        time: '1 hour ago',
        content: 'Thanks Dr. Priya! Will the live session cover Gradient Boosting as well?',
      },
      {
        author: 'Dr. Priya Sharma',
        avatar: 'PS',
        role: 'mentor',
        time: '45 mins ago',
        content: 'Yes, Vikram. We will spend the second half on XGBoost and LightGBM.',
      },
    ],
  },
  {
    id: 102,
    author: 'Amit Desai',
    avatar: 'AD',
    role: 'student',
    time: '5 hours ago',
    title: 'Question regarding Pandas merge vs join',
    tags: ['#python', '#pandas', '#module2'],
    badges: [],
    content:
      'I am working on the EDA assignment and getting confused between pd.merge() and df.join(). When should I use which? Does merge only work on columns and join on indexes?',
    likes: 8,
    comments: 1,
    replies: [
      {
        author: 'Neha Kumar',
        avatar: 'NK',
        role: 'student',
        time: '3 hours ago',
        content:
          'Basically yes! merge() is more versatile and can join on any columns (like SQL joins), while join() defaults to joining on the index. I usually just stick to merge() for everything.',
      },
    ],
  },
];

export const courseModules = [
  {
    id: 1,
    title: 'Module 1: Python for Data Science',
    shortTitle: 'Python for Data Science',
    icon: 'code',
    resources: 12,
    discussions: 34,
    description:
      'Build a strong Python foundation for data work — from variables and control flow to NumPy arrays, Pandas DataFrames, and exploratory plots. This module prepares you for statistics and machine learning in later weeks.',
    duration: '3 weeks',
    mentor: 'Dr. Meena Iyer',
    mentorRole: 'Statistics & EDA Lead',
    mentorAvatar: 'MI',
    status: 'In Progress',
    progress: 72,
    weekRange: 'Weeks 1–3',
    topics: [
      'Python syntax & data types',
      'Functions, loops & comprehensions',
      'NumPy arrays & vectorization',
      'Pandas: Series, DataFrames & indexing',
      'Data cleaning & missing values',
      'Matplotlib & Seaborn basics',
    ],
    resourcesList: [
      {
        id: 'm1-r1',
        type: 'pdf',
        icon: 'picture_as_pdf',
        name: 'Python for Data Science — Lecture Notes',
        desc: 'Full slide deck covering Week 1–3 topics with code snippets.',
        size: '4.2 MB',
        url: '#',
      },
      {
        id: 'm1-r2',
        type: 'link',
        icon: 'link',
        name: 'Colab: Pandas Practice Workbook',
        desc: 'Interactive exercises — filtering, groupby, merge, and pivot tables.',
        size: 'Notebook',
        url: 'https://colab.research.google.com',
      },
      {
        id: 'm1-r3',
        type: 'video',
        icon: 'play_circle',
        name: 'Live Session Recording: NumPy & Pandas Deep Dive',
        desc: '2h 15m session from May 12 — indexing tricks and performance tips.',
        size: '1h 52m',
        url: '#',
      },
      {
        id: 'm1-r4',
        type: 'pdf',
        icon: 'picture_as_pdf',
        name: 'Assignment 1 Starter Kit',
        desc: 'Dataset (sales_records.csv), rubric, and submission template.',
        size: '890 KB',
        url: '#',
      },
      {
        id: 'm1-r5',
        type: 'link',
        icon: 'link',
        name: 'Official Pandas Documentation — 10 Minutes to Pandas',
        desc: 'Recommended external reference for quick refresher.',
        size: 'External',
        url: 'https://pandas.pydata.org/docs/user_guide/10min.html',
      },
      {
        id: 'm1-r6',
        type: 'pdf',
        icon: 'picture_as_pdf',
        name: 'Cheat Sheet: NumPy & Pandas Quick Reference',
        desc: 'One-page printable reference for common operations.',
        size: '320 KB',
        url: '#',
      },
    ],
    discussionsList: [
      {
        id: 201,
        author: 'Kiran Reddy',
        avatar: 'KI',
        role: 'student',
        time: '3 hours ago',
        title: 'Best way to handle missing values in Pandas?',
        tags: ['#pandas', '#data-cleaning', '#module1'],
        badges: [{ text: 'Popular', class: 'badge-popular' }],
        content:
          'For the sales dataset in Assignment 1, should I use fillna with mean/median or drop rows? The rubric says "justify your approach" — what do mentors usually expect?',
        likes: 14,
        comments: 3,
        replies: [
          {
            author: 'Dr. Meena Iyer',
            avatar: 'MI',
            role: 'mentor',
            time: '2 hours ago',
            content:
              'Great question! There is no single right answer — document your reasoning. For numeric columns with <5% missing, median imputation is often fine. For categorical, mode or a separate "Unknown" category works. Never drop more than 10% without explaining why.',
          },
          {
            author: 'Amit Desai',
            avatar: 'AD',
            role: 'student',
            time: '1 hour ago',
            content: 'I used SimpleImputer from sklearn in my notebook — is that acceptable or should we stick to pure Pandas?',
          },
          {
            author: 'Dr. Meena Iyer',
            avatar: 'MI',
            role: 'mentor',
            time: '45 mins ago',
            content: 'Both are fine for this assignment. Focus on clarity in your write-up.',
          },
        ],
      },
      {
        id: 202,
        author: 'Rohan Mehta',
        avatar: 'RM',
        role: 'student',
        time: '1 day ago',
        title: 'List comprehension vs map() — which is more Pythonic?',
        tags: ['#python', '#module1'],
        badges: [],
        content:
          'In the Week 2 lab we used list comprehensions to filter rows. A classmate used map() with lambda. Is one preferred for readability in data science code?',
        likes: 6,
        comments: 2,
        replies: [
          {
            author: 'Neha Kumar',
            avatar: 'NK',
            role: 'student',
            time: '20 hours ago',
            content:
              'For simple transforms, comprehensions are usually clearer. For element-wise math on arrays, NumPy vectorization beats both.',
          },
          {
            author: 'Priya Nair',
            avatar: 'PR',
            role: 'student',
            time: '18 hours ago',
            content: '+1 — I only use map when chaining with other functional tools. Otherwise Pandas .apply() or vectorized ops.',
          },
        ],
      },
      {
        id: 203,
        author: 'Dr. Meena Iyer',
        avatar: 'MI',
        role: 'mentor',
        time: '2 days ago',
        title: 'Office hours this Friday — bring your Assignment 1 questions',
        tags: ['#office-hours', '#module1', '#assignment'],
        badges: [{ text: 'Mentor', class: 'badge-mentor' }],
        content:
          'I will host optional office hours Friday 6–7 PM IST. Zoom link is in the Resource Library. Please come with specific code or concept questions — we will do live debugging on shared notebooks.',
        likes: 31,
        comments: 1,
        replies: [
          {
            author: 'Vikram Patel',
            avatar: 'VP',
            role: 'student',
            time: '1 day ago',
            content: 'Will the recording be posted for those in US time zones?',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'Module 2: Statistics & EDA',
    shortTitle: 'Statistics & EDA',
    icon: 'bar_chart',
    resources: 15,
    discussions: 42,
    description:
      'Learn descriptive statistics, probability distributions, hypothesis testing, and exploratory data analysis workflows. Connect statistical thinking to visual insights in Python.',
    duration: '3 weeks',
    mentor: 'Dr. Meena Iyer',
    mentorRole: 'Statistics & EDA Lead',
    mentorAvatar: 'MI',
    status: 'Upcoming',
    progress: 0,
    weekRange: 'Weeks 4–6',
    topics: [
      'Descriptive statistics',
      'Probability & distributions',
      'Hypothesis testing',
      'Correlation & covariance',
      'EDA workflows & storytelling',
      'Seaborn advanced plots',
    ],
    resourcesList: [
      {
        id: 'm2-r1',
        type: 'pdf',
        icon: 'picture_as_pdf',
        name: 'Probability & Stats Cheat Sheet',
        desc: 'Distributions, z-tests, t-tests, and p-value interpretation guide.',
        size: '1.8 MB',
        url: '#',
      },
      {
        id: 'm2-r2',
        type: 'video',
        icon: 'play_circle',
        name: 'EDA Case Study: Customer Churn Dataset',
        desc: 'End-to-end exploratory analysis walkthrough.',
        size: '58 min',
        url: '#',
      },
      {
        id: 'm2-r3',
        type: 'link',
        icon: 'link',
        name: 'Colab: Hypothesis Testing Lab',
        desc: 'Practice t-tests, chi-square, and ANOVA with real datasets.',
        size: 'Notebook',
        url: '#',
      },
    ],
    discussionsList: [
      {
        id: 204,
        author: 'Amit Desai',
        avatar: 'AD',
        role: 'student',
        time: '5 hours ago',
        title: 'Question regarding Pandas merge vs join',
        tags: ['#python', '#pandas', '#module2'],
        badges: [],
        content:
          'I am working on the EDA assignment and getting confused between pd.merge() and df.join(). When should I use which?',
        likes: 8,
        comments: 1,
        replies: [
          {
            author: 'Neha Kumar',
            avatar: 'NK',
            role: 'student',
            time: '3 hours ago',
            content:
              'merge() is more versatile (like SQL joins); join() defaults to index. I usually stick to merge().',
          },
        ],
      },
      {
        id: 205,
        author: 'Nisha Sharma',
        avatar: 'NS',
        role: 'student',
        time: '2 days ago',
        title: 'When to use Spearman vs Pearson correlation?',
        tags: ['#statistics', '#module2'],
        badges: [],
        content: 'For skewed variables like income, should I default to Spearman? Any quick rule of thumb?',
        likes: 11,
        comments: 2,
        replies: [
          {
            author: 'Dr. Meena Iyer',
            avatar: 'MI',
            role: 'mentor',
            time: '1 day ago',
            content:
              'Pearson assumes linearity and roughly normal data. Spearman handles monotonic non-linear relationships and outliers better. Plot first!',
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: 'Module 3: Supervised Machine Learning',
    shortTitle: 'Supervised Machine Learning',
    icon: 'model_training',
    resources: 20,
    discussions: 56,
    description:
      'From linear regression to classification with logistic regression, decision trees, and model evaluation. Practice train/test splits, cross-validation, and metric selection.',
    duration: '4 weeks',
    mentor: 'Dr. Priya Sharma',
    mentorRole: 'ML & AI Lead',
    mentorAvatar: 'PS',
    status: 'Locked',
    progress: 0,
    weekRange: 'Weeks 7–10',
    topics: [
      'Linear & logistic regression',
      'Bias-variance tradeoff',
      'Decision trees & random forests',
      'Model evaluation metrics',
      'Cross-validation & hyperparameters',
      'Feature engineering basics',
    ],
    resourcesList: [
      {
        id: 'm3-r1',
        type: 'video',
        icon: 'play_circle',
        name: 'Live Session: Linear Regression',
        desc: 'Recording of Module 3 live session explaining OLS and residuals.',
        size: '1h 24m',
        url: '#',
      },
      {
        id: 'm3-r2',
        type: 'pdf',
        icon: 'picture_as_pdf',
        name: 'Scikit-learn Model Selection Guide',
        desc: 'Official-style reference for pipelines and GridSearchCV.',
        size: '2.1 MB',
        url: '#',
      },
    ],
    discussionsList: [
      {
        id: 206,
        author: 'Priya Nair',
        avatar: 'PR',
        role: 'student',
        time: '4 days ago',
        title: 'Accuracy vs F1 for imbalanced classification?',
        tags: ['#machine-learning', '#module3'],
        badges: [],
        content: 'Our fraud detection dataset is 98% negative class. Is accuracy misleading here?',
        likes: 19,
        comments: 2,
        replies: [
          {
            author: 'Dr. Priya Sharma',
            avatar: 'PS',
            role: 'mentor',
            time: '3 days ago',
            content: 'Yes — use precision, recall, F1, and ROC-AUC. Consider class weights or SMOTE.',
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Module 4: Advanced Ensemble Methods',
    shortTitle: 'Advanced Ensemble Methods',
    icon: 'account_tree',
    resources: 8,
    discussions: 12,
    description:
      'Bagging, boosting, stacking, and practical tuning of XGBoost and LightGBM. Apply ensembles to structured tabular competition-style problems.',
    duration: '2 weeks',
    mentor: 'Dr. Priya Sharma',
    mentorRole: 'ML & AI Lead',
    mentorAvatar: 'PS',
    status: 'Locked',
    progress: 0,
    weekRange: 'Weeks 11–12',
    topics: ['Random forests', 'Gradient boosting', 'XGBoost & LightGBM', 'Stacking ensembles', 'Feature importance'],
    resourcesList: [
      {
        id: 'm4-r1',
        type: 'video',
        icon: 'play_circle',
        name: 'Random Forest Walkthrough',
        desc: 'Step-by-step implementation from scratch and with sklearn.',
        size: '45 min',
        url: '#',
      },
      {
        id: 'm4-r2',
        type: 'pdf',
        icon: 'picture_as_pdf',
        name: 'Ensemble Methods Case Study',
        desc: 'Random Forest implementation notebook with Python and R examples.',
        size: '3.4 MB',
        url: '#',
      },
    ],
    discussionsList: [
      {
        id: 207,
        author: 'Dr. Priya Sharma',
        avatar: 'PS',
        role: 'mentor',
        time: '2 hours ago',
        title: 'Module 4 Resources Updated: Advanced Ensemble Methods',
        tags: ['#announcement', '#module4'],
        badges: [{ text: 'Announcement', class: 'badge-announcement' }],
        content:
          'New materials uploaded — review the Random Forest case study before Thursday live session. Python and R examples included.',
        likes: 24,
        comments: 2,
        replies: [
          {
            author: 'Vikram Patel',
            avatar: 'VP',
            role: 'student',
            time: '1 hour ago',
            content: 'Will the session cover Gradient Boosting as well?',
          },
          {
            author: 'Dr. Priya Sharma',
            avatar: 'PS',
            role: 'mentor',
            time: '45 mins ago',
            content: 'Yes — second half on XGBoost and LightGBM.',
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: 'Module 5: Deep Learning Foundations',
    shortTitle: 'Deep Learning Foundations',
    icon: 'psychology',
    resources: 5,
    discussions: 4,
    description:
      'Introduction to neural networks, backpropagation, CNNs for vision, and training best practices with PyTorch. Capstone prep for advanced DL track.',
    duration: '3 weeks',
    mentor: 'Rajesh Kumar',
    mentorRole: 'Data Engineering & DL',
    mentorAvatar: 'RK',
    status: 'Locked',
    progress: 0,
    weekRange: 'Weeks 13–15',
    topics: ['Neural network basics', 'Backpropagation', 'PyTorch tensors', 'CNNs', 'Transfer learning intro'],
    resourcesList: [
      {
        id: 'm5-r1',
        type: 'link',
        icon: 'link',
        name: 'PyTorch Official Tutorials',
        desc: 'Recommended prerequisite reading before Module 5 starts.',
        size: 'External',
        url: 'https://pytorch.org/tutorials/',
      },
    ],
    discussionsList: [
      {
        id: 208,
        author: 'Siddharth Roy',
        avatar: 'SR',
        role: 'student',
        time: '1 week ago',
        title: 'GPU requirements for Module 5 labs?',
        tags: ['#deep-learning', '#module5'],
        badges: [],
        content: 'Will Colab Pro be enough or do we need local CUDA setup?',
        likes: 7,
        comments: 1,
        replies: [
          {
            author: 'Rajesh Kumar',
            avatar: 'RK',
            role: 'mentor',
            time: '6 days ago',
            content: 'Free Colab is sufficient for all graded labs. Pro optional for faster iteration.',
          },
        ],
      },
    ],
  },
];

export const courseResources = [
  {
    id: 1,
    type: 'pdf',
    icon: 'picture_as_pdf',
    name: 'Probability & Stats Cheat Sheet',
    desc: 'Comprehensive guide for probability distributions and hypothesis testing.',
    module: 'Module 2',
  },
  {
    id: 2,
    type: 'video',
    icon: 'play_circle',
    name: 'Live Session: Linear Regression',
    desc: 'Recording of Module 3 Live Session explaining OLS.',
    module: 'Module 3',
  },
  {
    id: 3,
    type: 'link',
    icon: 'link',
    name: 'Colab: Pandas Exercises',
    desc: 'Practice exercises for Data Manipulation with Pandas.',
    module: 'Module 1',
  },
  {
    id: 4,
    type: 'pdf',
    icon: 'picture_as_pdf',
    name: 'Capstone Project Guidelines',
    desc: 'Rubric and rules for Capstone Phase 1 submission.',
    module: 'General',
  },
  {
    id: 5,
    type: 'video',
    icon: 'play_circle',
    name: 'Random Forest Walkthrough',
    desc: 'Step-by-step implementation of Random Forest from scratch.',
    module: 'Module 4',
  },
];

export const courseAnnouncements = [
  {
    id: 1,
    title: 'Assignment 3 Deadline Extended',
    date: 'May 18, 2026',
    content:
      'Due to several requests, the deadline for the Machine Learning Assignment 3 has been extended to May 22, 11:59 PM IST.',
    author: 'Admin Team',
  },
  {
    id: 2,
    title: 'Upcoming Hackathon: Data for Good',
    date: 'May 15, 2026',
    content:
      'Accredian is hosting a weekend hackathon next month. Form teams of 3-4 and solve a real-world predictive modeling problem. Registration opens tomorrow!',
    author: 'Admin Team',
  },
  {
    id: 3,
    title: 'New Mentor Onboarding',
    date: 'May 10, 2026',
    content:
      'Please welcome Rajesh Kumar, Senior Data Scientist at Amazon, who joins us as a mentor for the Deep Learning modules starting next week.',
    author: 'Admin Team',
  },
];
